
scoreboard players operation BINT REG = BINT CONST
scoreboard players set BINT CONST 10
data modify storage proc bintv set from storage proc sol

function aoc:proc/bigintreduce
data modify storage proc sol2 set from storage proc bintr

tellraw @a ["Solution : ", {"nbt":"sol2[-1]","storage":"proc"},{"nbt":"sol2[-2]","storage":"proc"},{"nbt":"sol2[-3]","storage":"proc"},{"nbt":"sol2[-4]","storage":"proc"},{"nbt":"sol2[-5]","storage":"proc"},{"nbt":"sol2[-6]","storage":"proc"},{"nbt":"sol2[-7]","storage":"proc"},{"nbt":"sol2[-8]","storage":"proc"},{"nbt":"sol2[-9]","storage":"proc"},{"nbt":"sol2[-10]","storage":"proc"},{"nbt":"sol2[-11]","storage":"proc"},{"nbt":"sol2[-12]","storage":"proc"},{"nbt":"sol2[-13]","storage":"proc"},{"nbt":"sol2[-14]","storage":"proc"},{"nbt":"sol2[-15]","storage":"proc"},{"nbt":"sol2[-16]","storage":"proc"},{"nbt":"sol2[-17]","storage":"proc"},{"nbt":"sol2[-18]","storage":"proc"},{"nbt":"sol2[-19]","storage":"proc"},{"nbt":"sol2[-20]","storage":"proc"},{"nbt":"sol2[-21]","storage":"proc"},{"nbt":"sol2[-22]","storage":"proc"},{"nbt":"sol2[-23]","storage":"proc"},{"nbt":"sol2[-24]","storage":"proc"},{"nbt":"sol2[-25]","storage":"proc"},{"nbt":"sol2[-26]","storage":"proc"},{"nbt":"sol2[-27]","storage":"proc"},{"nbt":"sol2[-28]","storage":"proc"},{"nbt":"sol2[-29]","storage":"proc"},{"nbt":"sol2[-30]","storage":"proc"},{"nbt":"sol2[-31]","storage":"proc"},{"nbt":"sol2[-32]","storage":"proc"},{"nbt":"sol2[-33]","storage":"proc"},{"nbt":"sol2[-34]","storage":"proc"},{"nbt":"sol2[-35]","storage":"proc"},{"nbt":"sol2[-36]","storage":"proc"},{"nbt":"sol2[-37]","storage":"proc"},{"nbt":"sol2[-38]","storage":"proc"},{"nbt":"sol2[-39]","storage":"proc"},{"nbt":"sol2[-40]","storage":"proc"},{"nbt":"sol2[-41]","storage":"proc"},{"nbt":"sol2[-42]","storage":"proc"},{"nbt":"sol2[-43]","storage":"proc"},{"nbt":"sol2[-44]","storage":"proc"},{"nbt":"sol2[-45]","storage":"proc"},{"nbt":"sol2[-46]","storage":"proc"},{"nbt":"sol2[-47]","storage":"proc"},{"nbt":"sol2[-48]","storage":"proc"},{"nbt":"sol2[-49]","storage":"proc"},{"nbt":"sol2[-50]","storage":"proc"},{"nbt":"sol2[-51]","storage":"proc"},{"nbt":"sol2[-52]","storage":"proc"},{"nbt":"sol2[-53]","storage":"proc"},{"nbt":"sol2[-54]","storage":"proc"},{"nbt":"sol2[-55]","storage":"proc"},{"nbt":"sol2[-56]","storage":"proc"},{"nbt":"sol2[-57]","storage":"proc"},{"nbt":"sol2[-58]","storage":"proc"},{"nbt":"sol2[-59]","storage":"proc"},{"nbt":"sol2[-60]","storage":"proc"},{"nbt":"sol2[-61]","storage":"proc"},{"nbt":"sol2[-62]","storage":"proc"},{"nbt":"sol2[-63]","storage":"proc"}]


scoreboard players operation BINT CONST = BINT REG